# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to npm

on:
  [push, pull_request]:
    branches: [master]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build and generate lib
        run: npm run build --if-present

      # - name: Configure git email
      #   run: git config --global user.email "mohammedehab93@gmail.com"

      # - name: Configure git username
      #   run: git config --global user.name "Mohammed Ehab"

      # - name: Update patch version
      #   run: npm version patch

      # - name: Commit updated patch to repo
      #   run: git commit -m "Updated patch version"

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
